---
title: Funding sources for undergraduate research in ecology and evolution
author: Connor French
description: Funding opportunities for EEB undergraduates to be aware of.
date: '2020-06-24'
aliases:   
  - ../funding-for-undergrads/
categories: 
  - Research
  - Resource
---

## Resources

### For students

#### Broad

Undergraduate Teaching Assistanceships

-   Opportunities vary per university, but check with your department and work-study websites for information. Sometimes these opportunities aren't advised well- if you have a class where you would like to do this, it doesn't hurt to ask the instructor about opportunities!

-   Here is an example program: [University of Texas College of Natural Sciences](https://cns.utexas.edu/tides/faculty/ugta-resources/students) [NSF Research Experiences for Undergraduates](https://www.nsf.gov/crssprgm/reu/)\
    [American Physiology Society Undergraduate Summer Research Fellowship](https://www.physiology.org/ugsrf?SSO=Y)

-   \$4,000 stipend, up to \$1,300 in EB travel expenses and a one year complimentary APS membership. 10 week position.

[Society of Wetland Scientists Student Research Grant](http://www.sws.org/Awards-and-Grants/student-research-grants.html)\
[Bat Conservation International Student Research Scholarship](http://www.batcon.org/our-work/initiatives/award-grants-scholarships)

-   Opens in October

[Garden Club of America Scholarships](https://www.gcamerica.org/scholarships)

-   There are a variety of scholarships available
-   Subject list: Botany, Coastal Wetland Studies, Conservation & Ecological Restoration, Desert Studies, Garden History & Design, Horticulture & Related Fields, International Work & Study, Landscape Architecture, Native Bird Habitat, Pollinator Research, Summer Environmental Study, Urban Forestry

[National Oceanic and Atmospheric Administration Ernest F. Hollings Undergraduate Scholarship](https://www.noaa.gov/office-education/hollings-scholarship)

-   Includes academic assistance (up to \$9500 per year) for two years and a 10-week paid summer internship (\$700 per week)

[Sigma Xi Grants in Aid of Research](https://www.sigmaxi.org/programs/grants-in-aid)

[Human-Environment Regional Observatory Fellowship](https://www.clarku.edu/departments/hero-program/)

-   Eight week stipend and academic credit

#### Local

[Hudson River Foundation Polgar Fellowship](https://www.hudsonriver.org/grants#polgar-fellowship)

-   \$5000 summertime grant in New York and New Jersey area

### For faculty

[NSF Facilitating Research at Primarily Undergraduate Universities](https://www.nsf.gov/funding/pgm_summ.jsp?pims_id=5518&org=NSF)

R01 supplements for URM students are available:\

<blockquote class="twitter-tweet">

<p lang="en" dir="ltr">

If you are an URM student and your mentor has an active R01, they could apply for a diversity supplement to cover your stipend, tuition, and up to 4K in institutional allowance. I also have a diversity supplement application to share. DM if interested.

</p>

--- Anny Reyes, MS (@annyreyesNeuro) <a href="https://twitter.com/annyreyesNeuro/status/1270755167818756098?ref_src=twsrc%5Etfw">June 10, 2020</a>

</blockquote>

```{=html}
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
```
### Databases

[Grants to Individuals](https://grantstoindividuals.org/)
